package autocode

type ServiceGroup struct {
	// Code generated by github.com/lhxlnsy/pap-go-server Begin; DO NOT EDIT.
	AutoCodeExampleService
	// Code generated by github.com/lhxlnsy/pap-go-server End; DO NOT EDIT.
}
