package autocode

type RouterGroup struct {
	// Code generated by github.com/lhxlnsy/pap-go-server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/lhxlnsy/pap-go-server End; DO NOT EDIT.
}
