package autocode

type ApiGroup struct {
	// Code generated by github.com/lhxlnsy/pap-go-server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/lhxlnsy/pap-go-server End; DO NOT EDIT.
}
